name: Gerar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install flet openpyxl

      - name: Gerar APK
        run: |
          flet build apk

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-vendas
          path: build/apk/*.apk
