      - name: Compilar APK Nativo
        run: flet build apk

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-vendas
          path: build/apk/app-release.apk
